CREATE TABLE TICKET (
    ID serial NOT NULL PRIMARY KEY,
    owner INTEGER,
    CRIATIONDATE DATE NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    TICKETNUMBER INTEGER,
    STATUS VARCHAR(255) NOT NULL,
    PRIORITY VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,
    assigned INTEGER,
    CONSTRAINT TICKET_USERACCOUNT_FKEY FOREIGN KEY (owner) REFERENCES USERACCOUNT (ID),
    CONSTRAINT TICKET_ASSIGNEDUSER_FKEY FOREIGN KEY (assigned) REFERENCES USERACCOUNT (ID)
);


CREATE TABLE CHANGESTATUS (
    ID serial NOT NULL PRIMARY KEY,
    TICKET INTEGER,
    userchange INTEGER,
    CRIATIONDATE DATE NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    CONSTRAINT CHANGESTATUS_TICKET_FKEY FOREIGN KEY (TICKET) REFERENCES TICKET (ID),
    CONSTRAINT TICKET_USERACCOUNT_FKEY FOREIGN KEY (userchange) REFERENCES USERACCOUNT (ID)
);

